

services:

  db:
    image: postgres:17

    container_name: smartdesk-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartdesk

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build: .

    container_name: smartdesk-backend

    restart: always

    depends_on:
      - db

    ports:
      - "8000:8000"

    env_file:
      - .env.docker


volumes:
  postgres_data: